# Generated by Django 3.0.6 on 2020-08-23 13:32

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=255)),
                ('Amount', models.FloatField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('Categories', models.CharField(choices=[('TRA', 'Travel'), ('MISC', 'Misc'), ('FOOD', 'Food'), ('ACCO', 'Accommodation'), ('TRAI', 'Training'), ('CERT', 'Certificate'), ('SP', 'Software Purchase')], max_length=5)),
                ('Trans_Date', models.DateField()),
                ('Image', models.ImageField(upload_to='')),
                ('Status', models.CharField(choices=[('PEND', 'Pending'), ('APPR', 'Approved'), ('REJ', 'Rejected')], default='Pending', max_length=5)),
                ('Date_of_Sub', models.DateField(default=datetime.datetime(2020, 8, 23, 19, 2, 28, 355603))),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
