# Generated by Django 3.0.6 on 2020-08-23 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assiapp', '0004_auto_20200823_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='Date_of_Sub',
            field=models.DateField(default=datetime.datetime(2020, 8, 23, 19, 37, 55, 443795)),
        ),
    ]
